assignments.pdf:assignments.tex ../FLOSS2022W.ics
	latexmk -pdf assignments

view:assignments.pdf
	okular assignments.pdf &

clean:
	rm assignments.aux assignments.fdb_latexmk assignments.fls assignments.log assignments.out assignments.pdf
